# Project-wide Gradle configuration
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX migration
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
code.style=official

# R8 full mode
android.enableR8.fullMode=true

# New build features
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
